### ISSUE TITLE
Build single database of existing donor records for analysis

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-crm#24]

**Comment by adamlofting** [comment]
@rebsd @valianttry @edrushka 

Please use this ticket to note ideas, or specific queries you would like to ask of this data when it is ready. 

E.g. % of 2013 donors who gave in 2014

and so on.

**Comment by RebsD** [comment]
Data exploration

Rationale: 
1. To get an overview of MoFo's 3MM constituents (join source? # active donors? how many do we have permission to communicate with? how many were one-off donors only?) 
1. To reduce the universe for targeted fundraising communications and campaigns. 
2. To get an understanding of donor behaviour to shape our communications and solicitations (e.g. give incentives for people to opt in, such as honouring our promise: “here’s why it’s important for us to be accountable to you for your generosity. please give us your email so we can do so."

Plan of action/segments for August/Sept fundraising communication
1. Stewardship communication targeting 2013-2014 donors. 
1. Stewardship communication for lapsed donors: "you’ve given at some point, here’s what we’ve been doing." 
2. Stewardship communication for those who've taken an action (to get them to wave their hand): "you’ve engaged with us before. Here’s what we’re doing/have done." Note: this constituents could be beyond donors and petition signers, as available data allows (Hive members, attendees of MozFest and Maker parties etc).  

Pull requests (and/or any other recency/frequency/value criteria you'd suggest or see in the data)
Individual donors: 
- personal info: name/address/email: do we have it? do we have permission to contact? 
- cumulative giving
- last gift amount
- highest gift amount
- number of gifts annually (excluding monthly donors) 
- retention/attrition rate for annual donors year over year

Monthly donors: 
- number of monthly donors
- number of gifts annually from monthly donors
- retention/attrition rates for monthly donors year over year

**Comment by RebsD** [comment]
I responded in Github, but here it is by email:


*Data exploration*

Rationale:

1. To get an overview of MoFo's 3MM constituents (join source? # active
donors? how many do we have permission to communicate with? how many were
one-off donors only?)

2. To reduce the universe for targeted fundraising communications and
campaigns.

3. To get an understanding of donor behaviour to shape our communications
and solicitations (e.g. give incentives for people to opt in, such as
honouring our promise: “here’s why it’s important for us to be accountable
to you for your generosity. please give us your email so we can do so."


*Plan of action/segments for August/Sept fundraising communication*

1. Stewardship communication targeting 2013-2014 donors.

2. Stewardship communication for lapsed donors: "you’ve given at some
point, here’s what we’ve been doing."

3. Stewardship communication for those who've taken an action (to get them
to wave their hand): "you’ve engaged with us before. Here’s what we’re
doing/have done." Note: this constituents could be beyond donors and
petition signers, as available data allows (Hive members, attendees of
MozFest and Maker parties etc).


*Pull requests (and/or any other recency/frequency/value data you'd suggest
or see in the data)*

*Individual donors*:

- personal info: name/address/email: do we have it? do we have permission
to contact?

- cumulative giving

- last gift amount

- highest gift amount

- # of gifts annually (excluding monthly donors)

- retention/attrition rate for annual donors year over year


*Monthly donors*:

- # of monthly donors

- # of gifts annually from monthly donors

- retention/attrition rates for monthly donors year over year

**Comment by adamlofting** [comment]
See also: https://github.com/MozillaFoundation/2015-fundraising/issues/9

**Comment by edrushka** [comment]
I'd also like to see opt-out rates. How many donors choose not to receive communications from us.

**Comment by edrushka** [comment]
Question, @adamlofting: what engagement actions will be mapped to SF? Will we know who signed a petition? Who hosted a Maker Party?

**Comment by valianttry** [comment]
@adamlofting are we going to be able to connect this new database to BSD or ExactTarget for email segmentation purposes? E.g. is this exercise producing a database primarily so that we can query it to answer these Qs, or will it also power "personalized tags" in our email communications? 

**BSD query on 8-17-2015 (note: PayPal data was not a part of this analysis unless noted)**
- Total number of email opt ins: 1,629,814 (not 3 million -- let's stop using that number, not sure where it came from)
- Total number of opt ins who have donated (all time): 247,292 (15% of total opt ins are donors)
- Total number of opt ins who have donated since Jan 1 2014: 137,797
- Total number of opt ins who donated during EOY 2014 (Nov 1 - Dec 31 2014): 122,140 (note this includes people who were opted in prior to the EOY campaign)
- Total number of NEW opt ins who both donated AND joined the list during EOY 2014 (Nov 1 - Dec 31 2014): 103,426

Monthly donor stats from January, 2015:
![small_dollar_fundraising_analysis_cy2014_for_infographic_-_google_sheets](https://cloud.githubusercontent.com/assets/9830371/9324159/9488651a-453c-11e5-9e70-6354a102e930.png)
- ~2200 opted to give monthly, leaving roughly 101,200 who opted to give 1x during EOY 2014 (97% give 1x)
- Total number of opt ins who have given at least 2x by credit card (all time): 25,032
- Total number of opt ins who have given at least 2x by credit card and are NOT recurring donors (all time): 23,830
- Total number of opt ins who have given at least 2x by credit card and are NOT recurring donors (past 12 months): 2,595
  **From Feb 2015 analysis:**
  ![alw___kjk_win_email_benchmarking_-_google_slides](https://cloud.githubusercontent.com/assets/9830371/9325121/fbdf0c02-4544-11e5-9442-9680922b294a.png)

![alw___kjk_win_email_benchmarking_-_google_slides](https://cloud.githubusercontent.com/assets/9830371/9325133/0fdf6d8c-4545-11e5-9a91-3862763d4e9e.png)

source: https://docs.google.com/presentation/d/1MMMct1fPx7kUq5VcySscl47JwlWd8fPyBBStL7tJ04s/edit#slide=id.g78ef8a5bd_00

**Comment by adamlofting** [comment]
Sorry, I missed this Q earlier...

> @adamlofting: what engagement actions will be mapped to SF? Will we know who signed a petition? Who hosted a Maker Party?

It's subject to what data teams have collected, and how much they want to integrate into SF. So in those two examples... Re: Petitions, yes, we'll definitely map this. Re: Maker Party, we didn't collect much data this year, we could map the old Webmaker Events website data if Teach team want to.

> @adamlofting are we going to be able to connect this new database to BSD or ExactTarget for email segmentation purposes?

End goal is that this database is Salesforce (this will be a Q4 project). And Salesforce will be connected to Exact Target. So, when you send an email through ET, you can make selections or personalization based on data in Salesforce (e.g. previous highest gift amount).

But, in the interim this is just a database for analysis and running some ad-hoc queries. It won't be integrated with our tooling.

**Comment by adamlofting** [comment]
This database exists now, and was used during EOY.

We should rescope future analysis as required.
